# Generated by Django 4.2.2 on 2023-06-08 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=3000)),
                ('anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('0', 'Visible'), ('1', 'Pending'), ('2', 'Deleted by Author'), ('3', 'Delted by Mods')], default='1', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=3000)),
                ('anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('0', 'Visible'), ('1', 'Pending'), ('2', 'Deleted by Author'), ('3', 'Delted by Mods')], default='1', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('linked_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoughts.thought')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thoughts.comment')),
            ],
        ),
        migrations.CreateModel(
            name='anonymousProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('linked_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thoughts.thought')),
            ],
        ),
    ]
