# Generated by Django 2.2.24 on 2023-06-08 17:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thoughts', '0003_comment_date_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='anonymousProfile',
            new_name='Anonymous_Profile',
        ),
    ]
