# Generated by Django 2.2.24 on 2023-06-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0004_auto_20230608_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymous_profile',
            name='anonymous_name',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thought',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
